export const Cars = [
	{
		name: 'Rolls-Royce Ghost',
		mileage: 2000,
		thumbnail: { xs: 'rolls_royce_120.png', sm: 'rolls_royce.png' },
		dailyPrice: 150,
		monthlyPrice: 3600,
		gearType: 'auto',
		gas: 'petrol',
	},
	{
		name: 'Tesla Model 3',
		mileage: 13000,
		thumbnail: { xs: 'tesla_m3_120.png', sm: 'tesla_m3.png' },
		dailyPrice: 90,
		monthlyPrice: 2200,
		gearType: 'auto',
		gas: 'electric',
	},
	{
		name: 'Audi S3',
		mileage: 10000,
		thumbnail: { xs: 'audi_s3_120.png', sm: 'audi_s3.png' },
		dailyPrice: 70,
		monthlyPrice: 1600,
		gearType: 'auto',
		gas: 'petrol',
	},
	{
		name: 'BMW M3',
		mileage: 10000,
		thumbnail: { xs: 'bmw_m3_120.png', sm: 'bmw_m3.png' },
		dailyPrice: 70,
		monthlyPrice: 1600,
		gearType: 'Manual',
		gas: 'petrol',
	},
	{
		name: 'Honda CR-V',
		mileage: 20000,
		thumbnail: { xs: 'honda_crv_120.png', sm: 'honda_crv.png' },
		dailyPrice: 60,
		monthlyPrice: 1600,
		gearType: 'auto',
		gas: 'petrol',
	},
	{
		name: 'Honda Accord',
		mileage: 20000,
		thumbnail: { xs: 'honda_accord_120.png', sm: 'honda_accord.png' },
		dailyPrice: 50,
		monthlyPrice: 1500,
		gearType: 'auto',
		gas: 'petrol',
	},
	{
		name: 'Jeep Wrangler',
		mileage: 20000,
		thumbnail: { xs: 'jeep_wrangler_120.png', sm: 'jeep_wrangler.png' },
		dailyPrice: 60,
		monthlyPrice: 1700,
		gearType: 'Manual',
		gas: 'diesel',
	},
	{
		name: 'Lamborghini Urus',
		mileage: 5000,
		thumbnail: { xs: 'lamborghini_urus_120.png', sm: 'lamborghini_urus.png' },
		dailyPrice: 150,
		monthlyPrice: 3800,
		gearType: 'auto',
		gas: 'petrol',
	},
];
