export const mockCars = [
	{
		id: '1',
		name: 'Rolls-Royce Ghost',
		mileage: 2000,
		thumbnail: { id: '1', xs: 'rolls_royce_120.png', sm: 'rolls_royce.png' },
		dailyPrice: 150,
		monthlyPrice: 3600,
		gearType: 'auto',
		gas: 'petrol',
	},
	{
		id: '2',
		name: 'Tesla Model 3',
		mileage: 13000,
		thumbnail: { id: '2', xs: 'tesla_m3_120.png', sm: 'tesla_m3.png' },
		dailyPrice: 90,
		monthlyPrice: 2200,
		gearType: 'auto',
		gas: 'electric',
	},
	{
		id: '3',
		name: 'Audi S3',
		mileage: 10000,
		thumbnail: { id: '3', xs: 'audi_s3_120.png', sm: 'audi_s3.png' },
		dailyPrice: 70,
		monthlyPrice: 1600,
		gearType: 'auto',
		gas: 'petrol',
	},
	{
		id: '4',
		name: 'BMW M3',
		mileage: 10000,
		thumbnail: { id: '4', xs: 'bmw_m3_120.png', sm: 'bmw_m3.png' },
		dailyPrice: 70,
		monthlyPrice: 1600,
		gearType: 'Manual',
		gas: 'petrol',
	},
	{
		id: '5',
		name: 'Honda CR-V',
		mileage: 20000,
		thumbnail: { id: '5', xs: 'honda_crv_120.png', sm: 'honda_crv.png' },
		dailyPrice: 60,
		monthlyPrice: 1600,
		gearType: 'auto',
		gas: 'petrol',
	},
	{
		id: '6',
		name: 'Honda Accord',
		mileage: 20000,
		thumbnail: { id: '6', xs: 'honda_accord_120.png', sm: 'honda_accord.png' },
		dailyPrice: 50,
		monthlyPrice: 1500,
		gearType: 'auto',
		gas: 'petrol',
	},
	{
		id: '7',
		name: 'Jeep Wrangler',
		mileage: 20000,
		thumbnail: {
			id: '7',
			xs: 'jeep_wrangler_120.png',
			sm: 'jeep_wrangler.png',
		},
		dailyPrice: 60,
		monthlyPrice: 1700,
		gearType: 'Manual',
		gas: 'diesel',
	},
	{
		id: '8',
		name: 'Lamborghini Urus',
		mileage: 5000,
		thumbnail: {
			id: '8',
			xs: 'lamborghini_urus_120.png',
			sm: 'lamborghini_urus.png',
		},
		dailyPrice: 150,
		monthlyPrice: 3800,
		gearType: 'auto',
		gas: 'petrol',
	},
];
